parameters:
  environmentName: ''
  deploymentName: ''

jobs:
- deployment: Deploy_${{parameters.environmentName}}
  pool: 'AzDevProdRMAgents'
  environment: ${{parameters.environmentName}}
  strategy:
  runOnce:
    deploy:     
      steps:
        - script: echo Deploying product update to ${{parameters.deploymentName}}
        